# Generated by Django 4.1.7 on 2023-03-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Volunteer', 'Volunteer'), ('Internship', 'Internship'), ('Other', 'Other')], max_length=255)),
                ('job_category', models.CharField(choices=[('Business', 'Business'), ('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Other', 'Other'), ('Education', 'Education'), ('Arts and entertainment', 'Arts and entertainment')], max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('application_deadline', models.DateField()),
                ('contact_info', models.CharField(max_length=255)),
            ],
        ),
    ]
