# Generated by Django 4.1.2 on 2023-04-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0002_alter_jobposting_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='job_category',
            field=models.CharField(choices=[('Business', 'Business'), ('Arts and entertainment', 'Arts and entertainment'), ('Other', 'Other'), ('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Education', 'Education')], max_length=255),
        ),
    ]
