# Generated by Django 4.1.2 on 2023-04-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
    ]
